/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import Clases.algoritmoDijkstra;
import Clases.datosDeGraficos;
import Clases.pintarDibujos;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Wcastañeda
 */
public class incio extends javax.swing.JFrame {

    private int numeroTope = 0;//este es el numero de nodos

    //este es el arbol de tipo clase de datosDeGraficos
    datosDeGraficos arboles = new datosDeGraficos();

    //tenemos el pintado de lineas
    //en un for anidado x y y donde comienza
    //x y y donde termina
    public static void pintarFiguras(int tope, datosDeGraficos arboles) {//pinta antes lo que esta en el panel
        for (int j = 0; j < tope; j++) {
            for (int k = 0; k < tope; k++) {
                if (arboles.getmAdyacencia(j, k) == 1) {
                    pintarDibujos.pintaLinea(miJlabel.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getCordeX(k), arboles.getCordeY(k), arboles.getmCoeficiente(j, k));
                }
            }
        }
        //en el caso de los circulos solo tienen una coordenada x y y
        for (int j = 0; j < tope; j++) {
            pintarDibujos.pintaCirculo(miJlabel.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), String.valueOf(arboles.getNombre(j)));
        }
    }

    /**
     * Creates new form incio
     */
    //inicializamos nuestros objetos y la interfaz
    public incio() {
        initComponents();
        cmbOrigen.setEnabled(false);
        cmbDestino.setEnabled(false);
        btnBuscarCaminoMasCorto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarCaminos = new javax.swing.JButton();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();
        btnBuscarCaminoMasCorto = new javax.swing.JButton();
        lblKmRecorridos = new java.awt.Label();
        miJlabel = new javax.swing.JLabel();
        lblLugarDePartida = new javax.swing.JLabel();
        lblLugarDeDestino = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        lblBuscaMejorRuta = new javax.swing.JLabel();
        lblMsj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        btnMostrarCaminos.setBackground(new java.awt.Color(0, 153, 153));
        btnMostrarCaminos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMostrarCaminos.setText("Mostrar Caminos");
        btnMostrarCaminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCaminosActionPerformed(evt);
            }
        });

        cmbOrigen.setBackground(new java.awt.Color(204, 255, 255));
        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jutiapa", "El Progreso", "Santa Catarina Mita", "Agua Blanca", "Asunción Mita", "Yupiltepeque", "Atescatempa", "Jerez", "El Adelanto", "Zapotitlán", "Comapa", "Jalpatagua", "Conguaco", "Moyuta", "Pasaco", "San José Acatempa", "Quezada", " " }));
        cmbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigenActionPerformed(evt);
            }
        });

        cmbDestino.setBackground(new java.awt.Color(204, 255, 255));
        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jutiapa", "El Progreso", "Santa Catarina Mita", "Agua Blanca", "Asunción Mita", "Yupiltepeque", "Atescatempa", "Jerez", "El Adelanto", "Zapotitlán", "Comapa", "Jalpatagua", "Conguaco", "Moyuta", "Pasaco", "San José Acatempa", "Quezada", " ", " " }));
        cmbDestino.setBorder(null);
        cmbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDestinoActionPerformed(evt);
            }
        });

        btnBuscarCaminoMasCorto.setBackground(new java.awt.Color(0, 153, 153));
        btnBuscarCaminoMasCorto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscarCaminoMasCorto.setText("Buscar Camino Mas Corto");
        btnBuscarCaminoMasCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCaminoMasCortoActionPerformed(evt);
            }
        });

        lblKmRecorridos.setBackground(new java.awt.Color(255, 0, 51));
        lblKmRecorridos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblKmRecorridos.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblKmRecorridos.setForeground(new java.awt.Color(51, 51, 255));
        lblKmRecorridos.setText("Kms");

        miJlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mapa_del_departamento_de_Jutiapa.gif"))); // NOI18N

        lblLugarDePartida.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblLugarDePartida.setForeground(new java.awt.Color(0, 0, 255));
        lblLugarDePartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLugarDePartida.setText("Lugar de Partida");

        lblLugarDeDestino.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblLugarDeDestino.setForeground(new java.awt.Color(0, 0, 255));
        lblLugarDeDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLugarDeDestino.setText("Lugar de Destino");

        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        txtArea1.setText("MUNICIPIOS DEL DEPARTAMENTO\n                DE JUTIAPA\n\n1. Jutiapa\n2. El Progreso\n3. Santa Catarina Mita\n4. Agua Blanca\n5. Asunción Mita\n6. Yupiltepeque\n7. Atescatempa\n8. Jerez\n9. El Adelanto\n10. Zapotitlán\n11. Comapa\n12. Jalpatagua\n13. Conguaco\n14. Moyuta,\n15. Pasaco\n16. San José Acatempa\n17. Quezada\n");
        jScrollPane1.setViewportView(txtArea1);

        lblBuscaMejorRuta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblBuscaMejorRuta.setForeground(new java.awt.Color(255, 0, 51));
        lblBuscaMejorRuta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscaMejorRuta.setText("OBTENER LA RUTA MAS CORTA");

        lblMsj.setBackground(new java.awt.Color(51, 102, 255));
        lblMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMsj.setForeground(new java.awt.Color(255, 0, 0));
        lblMsj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsj.setText(";)");
        lblMsj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarCaminos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarCaminoMasCorto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLugarDePartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLugarDeDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMsj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKmRecorridos, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBuscaMejorRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBuscaMejorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(miJlabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnMostrarCaminos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblLugarDePartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblLugarDeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnBuscarCaminoMasCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lblKmRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(lblMsj, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarCaminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCaminosActionPerformed

        cmbOrigen.setEnabled(true);
        miJlabel.paint(miJlabel.getGraphics());
        //le mandamos la matriz de adyacencia donde los municipios conectan
        //o no conectan (es necesario que los dos municipios conecten entre si)
        //si es 1 si tienen conexion y si es 0 no tiene conexion
        int matriz[][] = {
            {0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1},
            {1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1},
            {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0}
        };

        //esta es la matriz de coeficientes
        //esto es la distancia que hay entre cada municipio
        double coe[][] = {
            {0, 10, 0, 0, 0, 17, 0, 0, 0, 0, 43, 36, 0, 0, 0, 0, 20}, //1 jutiapa
            {10, 0, 20, 0, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},//2 progreso
            {0, 20, 0, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},//3 catocha
            {0, 0, 16, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},// 4agua blanca
            {0, 19, 17, 27, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},//5 asuncion mita
            {17, 0, 0, 0, 0, 0, 12, 15, 7.5, 9, 0, 0, 0, 0, 0, 0, 0},//6 yupiltepeque
            {0, 0, 0, 0, 24, 12, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0},//7 atescatempa
            {0, 0, 0, 0, 0, 15, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},//8 jerez
            {0, 0, 0, 0, 0, 7.5, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0},//9 adelante
            {0, 0, 0, 0, 0, 9, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0},//10 zapotitlan
            {43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0},//11 comapa
            {36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 15, 0, 0, 27, 0},//12 jalpatagua
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 7, 0, 0, 0},//13 conguaco
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 23, 0, 0},//14 moyuta
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0},//15 pasaco
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 15},//16 catempa
            {20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0}//17 quesada
        };
        //estas son las coordenadas de los vertices tanto en X como en Y
        //y el nombre que le daremos a cada nodo
        int xx1[] = {250, 286, 320, 400, 380, 310, 345, 335, 286, 300, 250, 180, 200, 165, 98, 135, 185};
        int yy1[] = {160, 109, 70, 50, 150, 195, 200, 256, 205, 250, 245, 225, 290, 285, 320, 150, 160};
        String nom[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"};

        //en este for le mandamos los parametros a los metodos set y get
        //tanto en set coordenada X , set coordenada Y y el nombre
        //estos parametros estan en la Clase datosDeGraficos
        for (int j = 0; j < 17; j++) {
            arboles.setCordeX(j, xx1[j]);
            arboles.setCordeY(j, yy1[j]);
            arboles.setNombre(j, nom[j]);
        }

        //aca le damos la adyacencia y el coeficiente
        //en el objeto de arboles
        for (int j = 0; j < 17; j++) {
            for (int k = 0; k < 17; k++) {
                arboles.setmAdyacencia(j, k, matriz[j][k]);
                arboles.setmCoeficiente(j, k, coe[j][k]);
            }
        }

        //le asignamos el tope
        //y pintamos las figuras
        numeroTope = 17;
        pintarFiguras(numeroTope, arboles);
    }//GEN-LAST:event_btnMostrarCaminosActionPerformed

    private void btnBuscarCaminoMasCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCaminoMasCortoActionPerformed

        cmbOrigen.setEnabled(false);
        cmbDestino.setEnabled(false);
        btnBuscarCaminoMasCorto.setEnabled(false);
        
        //inicializamos dos variables que es al punto donde llegaremos
        int origen = 0, destino = 0;
        String nombreOrigen, nombreDestino;
        nombreOrigen = (String) cmbOrigen.getSelectedItem(); //obtenemos el nombre de los items
        nombreDestino = (String) cmbDestino.getSelectedItem(); //obtenemos el nombre de los items

        //con estas condicionales les asignamos el nombre y el origen (seria el No, de cada nodo)
        if ((nombreOrigen.equals("Jutiapa"))) {
            origen = 0;
        } else if ((nombreOrigen.equals("El Progreso"))) {
            origen = 1;
        } else if ((nombreOrigen.equals("Santa Catarina Mita"))) {
            origen = 2;
        } else if ("Agua Blanca".equals(nombreOrigen)) {
            origen = 3;
        } else if ("Asunción Mita".equals(nombreOrigen)) {
            origen = 4;
        } else if ("Yupiltepeque".equals(nombreOrigen)) {
            origen = 5;
        } else if ("Atescatempa".equals(nombreOrigen)) {
            origen = 6;
        } else if ("Jerez".equals(nombreOrigen)) {
            origen = 7;
        } else if ("El Adelanto".equals(nombreOrigen)) {
            origen = 8;
        } else if ("Zapotitlán".equals(nombreOrigen)) {
            origen = 9;
        } else if ("Comapa".equals(nombreOrigen)) {
            origen = 10;
        } else if ("Jalpatagua".equals(nombreOrigen)) {
            origen = 11;
        } else if ("Conguaco".equals(nombreOrigen)) {
            origen = 12;
        } else if ("Moyuta".equals(nombreOrigen)) {
            origen = 13;
        } else if ("Pasaco".equals(nombreOrigen)) {
            origen = 14;
        } else if ("San José Acatempa".equals(nombreOrigen)) {
            origen = 15;
        } else if ("Quezada".equals(nombreOrigen)) {
            origen = 16;
        }

        //con estas condicionales les asignamos el nombre y el destino (seria el No, de cada nodo)
        if ((nombreDestino).equals("Jutiapa")) {
            destino = 0;
        } else if ((nombreDestino).equals("El Progreso")) {
            destino = 1;
        } else if ((nombreDestino).equals("Santa Catarina Mita")) {
            destino = 2;
        } else if ("Agua Blanca".equals(nombreDestino)) {
            destino = 3;
        } else if ("Asunción Mita".equals(nombreDestino)) {
            destino = 4;
        } else if ("Yupiltepeque".equals(nombreDestino)) {
            destino = 5;
        } else if ("Atescatempa".equals(nombreDestino)) {
            destino = 6;
        } else if ("Jerez".equals(nombreDestino)) {
            destino = 7;
        } else if ("El Adelanto".equals(nombreDestino)) {
            destino = 8;
        } else if ("Zapotitlán".equals(nombreDestino)) {
            destino = 9;
        } else if ("Comapa".equals(nombreDestino)) {
            destino = 10;
        } else if ("Jalpatagua".equals(nombreDestino)) {
            destino = 11;
        } else if ("Conguaco".equals(nombreDestino)) {
            destino = 12;
        } else if ("Moyuta".equals(nombreDestino)) {
            destino = 13;
        } else if ("Pasaco".equals(nombreDestino)) {
            destino = 14;
        } else if ("San José Acatempa".equals(nombreDestino)) {
            destino = 15;
        } else if ("Quezada".equals(nombreDestino)) {
            destino = 16;
        }

        //si el origen es == al destino
        if (origen == destino) {
            JOptionPane.showMessageDialog(null, "Estas en el mismo lugar: " + nombreOrigen + "\n Intentalo de Nuevo");//msj de error
        } else {
            //si es != al destino
            //ejecuta el algoritmo de Dijkstra
            String recorridos = "";
            algoritmoDijkstra dijkstra = new algoritmoDijkstra(arboles, numeroTope, origen, destino);
            dijkstra.dijkstra();
            Font fuente = new Font("Arial", Font.BOLD, 12);
            lblMsj.setFont(fuente);
            lblMsj.setText("Mostrando la Ruta \n Mas Corta " + ";)");
            lblMsj.setEnabled(true);
            lblMsj.setForeground(Color.red);
            lblKmRecorridos.setText("" + dijkstra.getAcumulado() + " Kms de Distancia");
        }

    }//GEN-LAST:event_btnBuscarCaminoMasCortoActionPerformed

    private void cmbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenActionPerformed
        cmbDestino.setEnabled(true);
    }//GEN-LAST:event_cmbOrigenActionPerformed

    private void cmbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoActionPerformed
        btnBuscarCaminoMasCorto.setEnabled(true);
    }//GEN-LAST:event_cmbDestinoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCaminoMasCorto;
    private javax.swing.JButton btnMostrarCaminos;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscaMejorRuta;
    public static java.awt.Label lblKmRecorridos;
    private javax.swing.JLabel lblLugarDeDestino;
    private javax.swing.JLabel lblLugarDePartida;
    private javax.swing.JLabel lblMsj;
    public static javax.swing.JLabel miJlabel;
    private javax.swing.JTextArea txtArea1;
    // End of variables declaration//GEN-END:variables

}
