/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Municipios;

import GrafosPkg.Grafo;

/**
 *
 * @author Wcastañeda
 */
public class Ventana extends javax.swing.JFrame {

    Grafo g = new Grafo("abcdefghijklmnopq");

    public Ventana() {
        g.agregarRuta('a', 'b', 10);
        g.agregarRuta('b', 'c', 20);
        g.agregarRuta('b', 'e', 19);
        g.agregarRuta('c', 'd', 18);
        g.agregarRuta('d', 'e', 27);
        g.agregarRuta('e', 'c', 17);
        g.agregarRuta('e', 'g', 24);
        g.agregarRuta('f', 'g', 12);
        g.agregarRuta('f', 'a', 17);
        g.agregarRuta('h', 'f', 12);
        g.agregarRuta('f', 'g', 15);
        g.agregarRuta('g', 'h', 12);
        g.agregarRuta('f', 'i', 10);
        g.agregarRuta('i', 'j', 9);
        g.agregarRuta('a', 'q', 20);
        g.agregarRuta('q', 'p', 15);
        g.agregarRuta('a', 'k', 43);
        g.agregarRuta('a', 'l', 36);
        g.agregarRuta('k', 'l', 16);
        g.agregarRuta('l', 'm', 15);
        g.agregarRuta('m', 'n', 10);
        g.agregarRuta('n', 'o', 23);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRespuesta = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lblKmsRecorridos = new javax.swing.JLabel();
        lblMapa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRespuesta.setBackground(new java.awt.Color(255, 0, 0));
        lblRespuesta.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblRespuesta.setForeground(new java.awt.Color(0, 0, 255));
        lblRespuesta.setText("-");

        cmbOrigen.setBackground(new java.awt.Color(153, 204, 255));
        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jutiapa", "El Progreso", "Santa Catarina Mita", "Agua Blanca", "Asunción Mita", "Yupiltepeque", "Atescatempa", "Jerez", "El Adelanto", "Zapotitlán", "Comapa", "Jalpatagua", "Conguaco", "Moyuta", "Pasaco", "San José Acatempa", "Quezada" }));

        cmbDestino.setBackground(new java.awt.Color(153, 204, 255));
        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jutiapa", "El Progreso", "Santa Catarina Mita", "Agua Blanca", "Asunción Mita", "Yupiltepeque", "Atescatempa", "Jerez", "El Adelanto", "Zapotitlán", "Comapa", "Jalpatagua", "Conguaco", "Moyuta", "Pasaco", "San José Acatempa", "Quezada" }));
        cmbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDestinoActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar Caminos Mas Corto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblKmsRecorridos.setBackground(new java.awt.Color(255, 0, 0));
        lblKmsRecorridos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblKmsRecorridos.setForeground(new java.awt.Color(51, 51, 255));
        lblKmsRecorridos.setText("-");

        lblMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mapa_del_departamento_de_Jutiapa.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Seleccione se Origen");

        lblDestino.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblDestino.setText("Seleccione se Destino");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setText("1. Jutiapa\n2. El Progreso\n3. Santa Catarina Mita\n4. Agua Blanca\n5. Asunción Mita\n6. Yupiltepeque\n7. Atescatempa\n8. Jerez\n9. El Adelanto\n10. Zapotitlán\n11. Comapa\n12. Jalpatagua\n13. Conguaco\n14. Moyuta\n15. Pasaco\n16. San José Acatempa\n17. Quezada");
        jScrollPane1.setViewportView(txtArea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENCUENTRA LA RUTA MAS CORTA EN EL MAPA DE JUTIAPA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKmsRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbDestino, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrigen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRespuesta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMapa)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblKmsRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String origen = cmbOrigen.getSelectedItem() + "";
        String destino = cmbDestino.getSelectedItem() + "";
        idMunicipio id = new idMunicipio();
        char idOrigen = id.MunicipiosJutiapa(origen);
        char idDestino = id.MunicipiosJutiapa(destino);
        String respuesta = g.encontrarRutaMinimaDijkstra(idOrigen, idDestino);
        lblRespuesta.setText(respuesta+ " Kms de Distancia");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDestinoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDestino;
    public static javax.swing.JLabel lblKmsRecorridos;
    private javax.swing.JLabel lblMapa;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
